import React, { useState } from 'react'
import { Card, CardHeader, CardContent } from '../ui/Card'
import {
  Lightbulb,
  CheckCircle2,
  ChevronDown,
  ChevronUp,
  Cpu,
  Sun,
  Activity,
  Zap,
} from 'lucide-react'

interface ForecastInsightsPanelProps {
  insights: string[]
  modelType?: string
}

export const ForecastInsightsPanel: React.FC<ForecastInsightsPanelProps> = ({
  insights,
  modelType = 'Random Forest Regressor',
}) => {
  const [showTechnicalDetails, setShowTechnicalDetails] = useState(false)

  const getInsightIcon = (index: number) => {
    switch (index) {
      case 0:
        return <Sun className="w-4 h-4 text-[#B09B29] dark:text-[#D4B838] shrink-0 mt-0.5" />
      case 1:
        return <Activity className="w-4 h-4 text-[#A0C878] shrink-0 mt-0.5" />
      case 2:
        return <Zap className="w-4 h-4 text-[#A0C878] shrink-0 mt-0.5" />
      default:
        return <CheckCircle2 className="w-4 h-4 text-[#788477] dark:text-[#859483] shrink-0 mt-0.5" />
    }
  }

  return (
    <Card className="border-[#DDD9C9] dark:border-[#2C3C2E]">
      <CardHeader
        title="Forecast Insights"
        subtitle="Derived operational characteristics from the 24-hour lookahead profile"
        icon={<Lightbulb className="w-4 h-4 text-[#B09B29] dark:text-[#D4B838]" />}
        action={
          <button
            type="button"
            onClick={() => setShowTechnicalDetails(!showTechnicalDetails)}
            className="flex items-center gap-1.5 text-[11px] font-mono text-[#788477] dark:text-[#859483] hover:text-[#26352A] dark:hover:text-[#F2F5ED] cursor-pointer transition-colors"
          >
            <span>Model Details</span>
            {showTechnicalDetails ? (
              <ChevronUp className="w-3.5 h-3.5" />
            ) : (
              <ChevronDown className="w-3.5 h-3.5" />
            )}
          </button>
        }
      />

      <CardContent className="p-4 sm:p-5 space-y-4">
        {/* Dynamic Insights List */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
          {insights.map((insight, idx) => (
            <div
              key={idx}
              className="p-3.5 rounded-lg bg-[#FAF6E9] dark:bg-[#1E2B20] border border-[#DDD9C9] dark:border-[#2C3C2E] flex items-start gap-3 shadow-2xs"
            >
              {getInsightIcon(idx)}
              <div className="text-xs text-[#26352A] dark:text-[#F2F5ED] leading-relaxed">
                {insight}
              </div>
            </div>
          ))}
        </div>

        {/* Expandable Technical Model Notes */}
        {showTechnicalDetails && (
          <div className="p-3.5 rounded-lg bg-[#FFFDF6] dark:bg-[#151F17] border border-[#DDD9C9] dark:border-[#2C3C2E] text-xs space-y-2 animate-in fade-in duration-200">
            <div className="flex items-center gap-2 font-mono font-bold text-[#26352A] dark:text-[#F2F5ED] text-[11px]">
              <Cpu className="w-3.5 h-3.5 text-[#A0C878]" />
              <span>Machine Learning Architecture</span>
            </div>
            <p className="text-[11px] text-[#506052] dark:text-[#C2CCC0] leading-relaxed">
              Forecast generated by the {modelType} engine. Predictions are constructed from diurnal cyclical trigonometric features (sin/cos temporal coordinates) and calibrated against historical baseline feeder demand profiles.
            </p>
            <div className="flex flex-wrap gap-2 pt-1 text-[10px] font-mono text-[#788477] dark:text-[#859483]">
              <span className="px-2 py-0.5 rounded bg-[#FAF6E9] dark:bg-[#1E2B20] border border-[#DDD9C9] dark:border-[#2C3C2E]">
                Algorithm: {modelType}
              </span>
              <span className="px-2 py-0.5 rounded bg-[#FAF6E9] dark:bg-[#1E2B20] border border-[#DDD9C9] dark:border-[#2C3C2E]">
                Horizon: 24h lookahead
              </span>
              <span className="px-2 py-0.5 rounded bg-[#FAF6E9] dark:bg-[#1E2B20] border border-[#DDD9C9] dark:border-[#2C3C2E]">
                Granularity: 1-Hour Timesteps
              </span>
            </div>
          </div>
        )}
      </CardContent>
    </Card>
  )
}

export default ForecastInsightsPanel
