import React, { useState } from 'react'
import { Card, CardHeader, CardContent } from '../ui/Card'
import {
  Lightbulb,
  CheckCircle2,
  ChevronDown,
  ChevronUp,
  Cpu,
  Sun,
  Activity,
  Zap,
} from 'lucide-react'

interface ForecastInsightsPanelProps {
  insights: string[]
  modelType?: string
}

export const ForecastInsightsPanel: React.FC<ForecastInsightsPanelProps> = ({
  insights,
  modelType = 'Random Forest Regressor',
}) => {
  const [showTechnicalDetails, setShowTechnicalDetails] = useState(false)

  const getInsightIcon = (index: number) => {
    switch (index) {
      case 0:
        return <Sun className="w-4 h-4 text-amber-500 shrink-0 mt-0.5" />
      case 1:
        return <Activity className="w-4 h-4 text-[#047857] dark:text-[#86EFAC] shrink-0 mt-0.5" />
      case 2:
        return <Zap className="w-4 h-4 text-[#10B981] shrink-0 mt-0.5" />
      default:
        return <CheckCircle2 className="w-4 h-4 text-[#047857] dark:text-[#86EFAC] shrink-0 mt-0.5" />
    }
  }

  return (
    <Card className="border-[#BBF7D0]/70 dark:border-[#86EFAC]/25 bg-white/90 dark:bg-[#122C1F]/90 backdrop-blur-md shadow-[0_8px_25px_rgba(16,80,55,0.06)] dark:shadow-[0_8px_25px_rgba(0,0,0,0.3)] transition-all duration-300">
      <CardHeader
        title="Forecast Insights"
        subtitle="Derived operational characteristics from the 24-hour lookahead profile"
        icon={<Lightbulb className="w-4 h-4 text-amber-500" />}
        action={
          <button
            type="button"
            onClick={() => setShowTechnicalDetails(!showTechnicalDetails)}
            className="flex items-center gap-1.5 text-[11px] font-mono text-[#425B4C] dark:text-[#A7F3D0] hover:text-[#10251A] dark:hover:text-white cursor-pointer transition-colors"
          >
            <span>Model Details</span>
            {showTechnicalDetails ? (
              <ChevronUp className="w-3.5 h-3.5" />
            ) : (
              <ChevronDown className="w-3.5 h-3.5" />
            )}
          </button>
        }
      />

      <CardContent className="p-4 sm:p-5 space-y-4">
        {/* Dynamic Insights List */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
          {insights.map((insight, idx) => (
            <div
              key={idx}
              className="p-3.5 rounded-2xl bg-[#F4FAF5] dark:bg-[#0E2419]/90 border border-[#BBF7D0]/60 dark:border-[#86EFAC]/20 flex items-start gap-3 shadow-2xs hover:-translate-y-0.5 hover:shadow-md transition-all duration-200"
            >
              {getInsightIcon(idx)}
              <div className="text-xs text-[#10251A] dark:text-white leading-relaxed font-medium">
                {insight}
              </div>
            </div>
          ))}
        </div>

        {/* Expandable Technical Model Notes */}
        {showTechnicalDetails && (
          <div className="p-4 rounded-2xl bg-white/95 dark:bg-[#0E2419]/95 border border-[#BBF7D0]/70 dark:border-[#86EFAC]/25 text-xs space-y-2 animate-in fade-in duration-200 shadow-md">
            <div className="flex items-center gap-2 font-mono font-bold text-[#10251A] dark:text-white text-[11px]">
              <Cpu className="w-3.5 h-3.5 text-[#047857] dark:text-[#86EFAC]" />
              <span>Machine Learning Architecture</span>
            </div>
            <p className="text-[11px] text-[#425B4C] dark:text-[#A7F3D0] leading-relaxed font-medium">
              Forecast generated by the {modelType} engine. Predictions are constructed from diurnal cyclical trigonometric features (sin/cos temporal coordinates) and calibrated against historical baseline feeder demand profiles.
            </p>
            <div className="flex flex-wrap gap-2 pt-1 text-[10px] font-mono text-[#047857] dark:text-[#86EFAC]">
              <span className="px-2.5 py-1 rounded-full bg-[#ECFDF3] dark:bg-[#064E3B]/50 border border-[#BBF7D0] dark:border-[#86EFAC]/30 font-semibold">
                Algorithm: {modelType}
              </span>
              <span className="px-2.5 py-1 rounded-full bg-[#ECFDF3] dark:bg-[#064E3B]/50 border border-[#BBF7D0] dark:border-[#86EFAC]/30 font-semibold">
                Horizon: 24h lookahead
              </span>
              <span className="px-2.5 py-1 rounded-full bg-[#ECFDF3] dark:bg-[#064E3B]/50 border border-[#BBF7D0] dark:border-[#86EFAC]/30 font-semibold">
                Granularity: 1-Hour Timesteps
              </span>
            </div>
          </div>
        )}
      </CardContent>
    </Card>
  )
}

export default ForecastInsightsPanel
